; ==================================================================================
; ==================================================================================
;  LIFE OF CRIME - VANILLA HAIR REMAKE SMP SPELL DISTRIBUTION
; ==================================================================================

; Arcus Crowborn
Spell = _Uvi_NordHair02Spell|LOCArcus|NONE|NONE

; Arisa Hawkblood
Spell = _Uvi_NordHair07Spell|LOC03Leader|NONE|NONE

; Athlynn
Spell = _Uvi_ElfHair07Spell|LOCBrothelAthlynn|NONE|NONE

; Adine
Spell = _Uvi_NordHair11Spell|LOCAdine|NONE|NONE

; Adine 
Spell = _Uvi_NordHair11Spell|LOCAdineDead|NONE|NONE

; Alerio
Spell = _Uvi_NordHair02Spell|LOCFortTrainer|NONE|NONE

; Anetta Hawkblood
Spell = _Uvi_NordHair12Spell|LOC03Anetta|NONE|NONE

; Adamio Hawkblood
Spell = _Uvi_NordHair13Spell|LOC02Thug|NONE|NONE

; Sarvar
Spell = _Uvi_NordHair06Spell|LOCBrothelSarvar|NONE|NONE

; Oriva Crowborn
Spell = _Uvi_NordHair03Spell|LOCOriva|NONE|NONE

; Tharod
Spell = _Uvi_NordHair02Spell|LOCTharod|NONE|NONE

; Erika
Spell = _Uvi_NordHair09Spell|LOCErika|NONE|NONE

; Ormintus
Spell = _Uvi_NordHair12Spell|LOCFortHealer|NONE|NONE

; Natessa
Spell = _Uvi_DarkElfHair05Spell|LOCBrothelNatessa|NONE|NONE

; Mattius
Spell = _Uvi_NordHair11Spell|LOCBrothelMattius|NONE|NONE

; Margretta Hawkblood
Spell = _Uvi_NordHair19Spell|LOCAnetta01Mother|NONE|NONE

; Lutherus
Spell = _Uvi_NordHair15Spell|LOC05Thug|NONE|NONE

; Hunalf
Spell = _Uvi_NordHair19Spell|LOC01Thug|NONE|NONE

; Hilsi
Spell = _Uvi_NordHair09Spell|LOCBrothelLaylana|NONE|NONE

; Emerald
Spell = _Uvi_NordHair14Spell|LOCBrothelEmerald|NONE|NONE

; Brothel Doorman
Spell = _Uvi_NordHair12Spell|LOCBrothelDoorman|NONE|NONE

; Crowborn Operative
Spell = _Uvi_NordHair03Spell|LOCR07Receiver|NONE|NONE

; Sifgelf
Spell = _Uvi_NordHair19Spell|LOCTMarkarthTarget|NONE|NONE

; Bramion
Spell = _Uvi_DarkElfHair04Spell|LOCTSolitudeTarget|NONE|NONE

; Captain Hjaling
Spell = _Uvi_NordHair05Spell|LOCTFalkreathTarget|NONE|NONE

; Captain Jalgi
Spell = _Uvi_NordHair21Spell|LOC04Captain|NONE|NONE

; Captain Ventano
Spell = _Uvi_DarkElfHair05Spell|LOCHeistBoss|NONE|NONE

; Aldta
Spell = _Uvi_NordHair02Spell|LOCTFalkreathBrawler02|NONE|NONE

; Fralla Favance
Spell = _Uvi_NordHair14Spell|LOCTDawnstarTarget|NONE|NONE

; Vigtilde
Spell = _Uvi_NordHair11Spell|LOCTWindhelmTarget|NONE|NONE

; Hired Thug
Spell = _Uvi_NordHair16Spell|LOCTRiftenThug|NONE|NONE

; Stonehills Miner
Spell = _Uvi_OrcHair17Spell|LOCTMorthalMiner|NONE|NONE

; Deadbeat
Spell = _Uvi_NordHair03Spell|LOCR09Deadbeat|NONE|NONE

; EncBuyer03
Spell = _Uvi_NordHair07Spell|LOCEncBuyer03|NONE|NONE

; EncBuyer04
Spell = _Uvi_NordHair09Spell|LOCEncBuyer04|NONE|NONE

; EncOperative01
Spell = _Uvi_NordHair05Spell|LOCEncOperative01|NONE|NONE

; EncOperative02
Spell = _Uvi_NordHair05Spell|LOCEncOperative02|NONE|NONE

; EncOperative03
Spell = _Uvi_NordHair14Spell|LOCEncOperative03|NONE|NONE

; EncOperative05
Spell = _Uvi_DarkElfHair08Spell|LOCEncOperative05|NONE|NONE

; EncOperative06
Spell = _Uvi_NordHair04Spell|LOCEncOperative06|NONE|NONE

; EncOperative08
Spell = _Uvi_NordHair07Spell|LOCEncOperative08|NONE|NONE

; EncOperative09
Spell = _Uvi_NordHair08Spell|LOCEncOperative09|NONE|NONE

; EncOperative10
Spell = _Uvi_RedguardHair05Spell|LOCEncOperative10|NONE|NONE

; EncOperative11
Spell = _Uvi_DarkElfHair02Spell|LOCEncOperative11|NONE|NONE

; EncOperative12
Spell = _Uvi_NordHair05Spell|LOCEncOperative12|NONE|NONE

; EncOperative14
Spell = _Uvi_ElfHair07Spell|LOCEncOperative14|NONE|NONE

; EncOperative15
Spell = _Uvi_NordHair20Spell|LOCEncOperative15|NONE|NONE

; EncEnforcer01
Spell = _Uvi_NordHair03Spell|LOCEncEnforcer01|NONE|NONE

; EncEnforcer04
Spell = _Uvi_NordHair07Spell|LOCEncEnforcer04|NONE|NONE

; EncEnforcer05
Spell = _Uvi_DarkElfHair01Spell|LOCEncEnforcer05|NONE|NONE

; EncEnforcer06
Spell = _Uvi_ElfHair03Spell|LOCEncEnforcer06|NONE|NONE

; EncEnforcer07
Spell = _Uvi_NordHair01Spell|LOCEncEnforcer07|NONE|NONE

; EncEnforcer09
Spell = _Uvi_NordHair18Spell|LOCEncEnforcer09|NONE|NONE

; EncEnforcer10
Spell = _Uvi_DarkElfHair07Spell|LOCEncEnforcer10|NONE|NONE

; EncEnforcer11
Spell = _Uvi_DarkElfHair08Spell|LOCEncEnforcer11|NONE|NONE

; EncEnforcer13
Spell = _Uvi_DarkElfHair09Spell|LOCEncEnforcer13|NONE|NONE

; EncEnforcer14
Spell = _Uvi_NordHair11Spell|LOCEncEnforcer14|NONE|NONE

; EncEnforcer16
Spell = _Uvi_NordHair03Spell|LOCEncEnforcer16|NONE|NONE

; EncEnforcer17
Spell = _Uvi_NordHair12Spell|LOCEncEnforcer17|NONE|NONE

; EncEnforcer18
Spell = _Uvi_NordHair17Spell|LOCEncEnforcer18|NONE|NONE

; EncEnforcer19
Spell = _Uvi_NordHair13Spell|LOCEncEnforcer19|NONE|NONE

; EncEnforcer20
Spell = _Uvi_DarkElfHair06Spell|LOCEncEnforcer20|NONE|NONE

; EncEnforcer21
Spell = _Uvi_ElfHair03Spell|LOCEncEnforcer21|NONE|NONE

; EncEnforcer22
Spell = _Uvi_OrcHair03Spell|LOCEncEnforcer22|NONE|NONE

; EncEnforcer23
Spell = _Uvi_OrcHair12Spell|LOCEncEnforcer23|NONE|NONE

; EncEnforcer24
Spell = _Uvi_DarkElfHair02Spell|LOCEncEnforcer24|NONE|NONE

; EncEnforcer25
Spell = _Uvi_NordHair10Spell|LOCEncEnforcer25|NONE|NONE

; LOCFortAlchemist
Spell = _Uvi_NordHair09Spell|LOCFortAlchemist|NONE|NONE

; LOCFortBlacksmith
Spell = _Uvi_NordHair04Spell|LOCFortBlacksmith|NONE|NONE

; --- Patrons ---

Spell = _Uvi_NordHair01Spell|LOCBrothelPatron|NONE|NONE|NONE|NONE|10

Spell = _Uvi_NordHair02Spell|LOCBrothelPatron|NONE|NONE|NONE|NONE|10

Spell = _Uvi_NordHair03Spell|LOCBrothelPatron|NONE|NONE|NONE|NONE|10

Spell = _Uvi_NordHair05Spell|LOCBrothelPatron|NONE|NONE|NONE|NONE|10

Spell = _Uvi_NordHair06Spell|LOCBrothelPatron|NONE|NONE|NONE|NONE|10

Spell = _Uvi_NordHair08Spell|LOCBrothelPatron|NONE|NONE|NONE|NONE|10

Spell = _Uvi_NordHair09Spell|LOCBrothelPatron|NONE|NONE|NONE|NONE|10

Spell = _Uvi_NordHair11Spell|LOCBrothelPatron|NONE|NONE|NONE|NONE|10

Spell = _Uvi_NordHair15Spell|LOCBrothelPatron|NONE|NONE|NONE|NONE|10

Spell = _Uvi_NordHair19Spell|LOCBrothelPatron|NONE|NONE|NONE|NONE|10

