; ==================================================================================
;  A TALE OF BLOOD AND SNOW - VANILLA HAIR REMAKE SMP SPELL DISTRIBUTION
; ==================================================================================

; Vlkoslak 
Spell = _Uvi_NordHair02Spell|DV01Vlkoslak~ATaleOfBloodAndSnow.esm|NONE|NONE

; Domna Magia 
Spell = _Uvi_NordHair01Spell|DV01DomnaMagia~ATaleOfBloodAndSnow.esm|NONE|NONE

; Jelkar 
Spell = _Uvi_NordHair07Spell|DV01Jelkar~ATaleOfBloodAndSnow.esm|NONE|NONE

; Viatrix Caerellia 
Spell = _Uvi_NordHair12Spell|DV01CyrodiilVampiriumAgent~ATaleOfBloodAndSnow.esm|NONE|NONE

; Viellia Carmalo 
Spell = _Uvi_NordHair12Spell|DV01ViatrixDisguised~ATaleOfBloodAndSnow.esm|NONE|NONE

; Ciirta Antabolis 
Spell = _Uvi_NordHair09Spell|DV01VigilantLeader~ATaleOfBloodAndSnow.esm|NONE|NONE

; Berne Faction Boss 
Spell = _Uvi_NordHair02Spell|DV01BerneBoss~ATaleOfBloodAndSnow.esm|NONE|NONE

; Stormcaller Boss 
Spell = _Uvi_NordHair13Spell|DV01StormcallerBoss~ATaleOfBloodAndSnow.esm|NONE|NONE

; Raelynne Belette 
Spell = _Uvi_NordHair06Spell|DV01VigilantRaelynne~ATaleOfBloodAndSnow.esm|NONE|NONE

; Vidkun Fang-Breaker 
Spell = _Uvi_NordHair10Spell|DV01VigilantVidkun~ATaleOfBloodAndSnow.esm|NONE|NONE

; Velfred 
Spell = _Uvi_NordHair16Spell|DV01CronvangrVelfred~ATaleOfBloodAndSnow.esm|NONE|NONE

; Narina Evicus 
Spell = _Uvi_NordHair14Spell|DV01CronvangrNarina~ATaleOfBloodAndSnow.esm|NONE|NONE

; Rakoslod 
Spell = _Uvi_NordHair06Spell|DV01CronvangrRakoslod~ATaleOfBloodAndSnow.esm|NONE|NONE

; Aenar 
Spell = _Uvi_NordHair09Spell|DV01QuarraAenar~ATaleOfBloodAndSnow.esm|NONE|NONE

; Malielle Masoriane 
Spell = _Uvi_NordHair14Spell|DV01QuarraMalielle~ATaleOfBloodAndSnow.esm|NONE|NONE

; Haesmar 
Spell = _Uvi_NordHair05Spell|DV01QuarraHaesmar~ATaleOfBloodAndSnow.esm|NONE|NONE

; Rothis Dolovas 
Spell = _Uvi_DarkElfHair01Spell|DV01QuarraTraitor~ATaleOfBloodAndSnow.esm|NONE|NONE
