; ==================================================================================
;  LEGACY OF ORSINIUM - VANILLA HAIR REMAKE SMP SPELL DISTRIBUTION
; ==================================================================================

; Shaol (HairFemaleOrc14)
Spell = _Uvi_OrcHair14Spell|LO_NB01_OrcWife_Shaol|NONE|NONE

; Lasha (HairFemaleOrc06)
Spell = _Uvi_OrcHair06Spell|LO_NB01_OrcWife_Lasha|NONE|NONE

; Galka (HairFemaleOrc07)
Spell = _Uvi_OrcHair07Spell|LO_NB01_OrcWife_Galka|NONE|NONE

; Hunt-Wife Durga (HairFemaleOrc05)
Spell = _Uvi_OrcHair05Spell|LO_HuntWife|NONE|NONE

; Executioner Garrug (HairMaleOrc26)
Spell = _Uvi_OrcHair26Spell|LO_Executioner|NONE|NONE

; High Priest Agrok (HairMaleOrc05)
Spell = _Uvi_OrcHair05Spell|LO_Agrok|NONE|NONE

; Shade of Agrok (HairMaleOrc05)
Spell = _Uvi_OrcHair05Spell|LO_AgrokShade|NONE|NONE

; Archivist Torg (HairMaleOrc09)
Spell = _Uvi_OrcHair09Spell|LO_ArchivistTorg|NONE|NONE

; Bosh gro-Murtag (HairMaleOrc08)
Spell = _Uvi_OrcHair08Spell|LO_Blacksmith|NONE|NONE

; Dulfish (HairMaleOrc02)
Spell = _Uvi_OrcHair02Spell|LO_ACREx02Dulfish|NONE|NONE

; Yashnag gro-Yazgu (HairMaleOrc23)
Spell = _Uvi_OrcHair23Spell|LO_Yashnag~|NONE|NONE

; Yashnag gro-Yazgu (HairMaleOrc23)
Spell = _Uvi_OrcHair23Spell|LO_ACQ03Yashnag~|NONE|NONE

; Batum gra-Bar (HairFemaleOrc14)
Spell = _Uvi_OrcHair14Spell|LO_ACQ03AspirantBatum|NONE|NONE

; Guardsman Yorrik (HairMaleNord05)
Spell = _Uvi_NordHair05Spell|LO_LB01GuardYorrik|NONE|NONE

; Feran Dreth (HairMaleDarkElf06)
Spell = _Uvi_DarkElfHair06Spell|LO_LB01Dreth|NONE|NONE

; Murdyn Grulen (HairMaleDarkElf02)
Spell = _Uvi_DarkElfHair02Spell|LO_ChampionBoethiah|NONE|NONE

; Urgo Ironheart (HairMaleDarkElf02)
Spell = _Uvi_DarkElfHair02Spell|LO_ACSideHW03Champion|NONE|NONE

; Sil (HairFemaleElf05 -> High Elf 05)
Spell = _Uvi_ElfHair05Spell|LO_ACQ03Silhansa|NONE|NONE

; Sil (HairFemaleElf05 -> High Elf 05)
Spell = _Uvi_ElfHair05Spell|LO_Silhansa|NONE|NONE

; Vaynth Shadowweaver (HairFemaleDarkElf05)
Spell = _Uvi_DarkElfHair05Spell|LO_MQ02aCultistBoss|NONE|NONE

; Dead Orc (HairMaleOrc24)
Spell = _Uvi_OrcHair24Spell|LO_MQ02aMercenaryCorpse|NONE|NONE

; Orc Miner Male 1 (HairMaleOrc24)
Spell = _Uvi_OrcHair24Spell|LO_MQ01MinerBrute|NONE|NONE

; Orc Miner Male 2 (HairMaleOrc24)
Spell = _Uvi_OrcHair24Spell|LO_MQ01MinerStoic|NONE|NONE

; Orc Miner Female (HairFemaleOrc17)
Spell = _Uvi_OrcHair17Spell|LO_MQ01MinerFemale|NONE|NONE

; Orc Ghost Miner (HairMaleOrc24)
Spell = _Uvi_OrcHair24Spell|LO_EncOrcGhostMiner01_CC|NONE|NONE
